#include "obfuscator.h"
#include <string>
#include <vector>
#include <sstream>
#include <iomanip>
#include <ctime>
#include "../imgui/imgui.h"

namespace Obfuscator {
    
    char inputBuffer[1024] = "MySecretPassword";
    char outputBuffer[4096] = "";
    int junkLines = 5;
    bool enableXor = true;

    unsigned char RandomByte() {
        return (unsigned char)(rand() % 256);
    }

    std::string ObfuscateString(const std::string& input, const std::string& varName) {
        if (input.empty()) return "";
        
        unsigned char key = RandomByte();
        if (key == 0) key = 0x55; 

        std::stringstream ss;
        ss << "// Obfuscated String: \"" << input << "\"\n";
        ss << "unsigned char " << varName << "_key = 0x" << std::hex << (int)key << ";\n";
        ss << "char " << varName << "[] = { ";
        
        for (size_t i = 0; i < input.length(); i++) {
            unsigned char enc = input[i] ^ key;
            ss << "0x" << std::hex << (int)enc;
            if (i < input.length() - 1) ss << ", ";
        }
        ss << ", 0x00 };\n"; 
        
        ss << "for(int i = 0; i < " << std::dec << input.length() << "; i++) {\n";
        ss << "    " << varName << "[i] ^= " << varName << "_key;\n";
        ss << "}\n";
        ss << varName << "[" << input.length() << "] = '\\0';\n";
        
        return ss.str();
    }

    std::string GenerateJunkCode(int lines) {
        std::stringstream ss;
        ss << "// JUNK CODE START (Confuse Decompiler)\n";
        ss << "{\n";
        
        for (int i = 0; i < lines; i++) {
            int op = rand() % 4;
            std::string var = "junk_" + std::to_string(rand() % 1000);
            int val1 = rand() % 100;
            int val2 = rand() % 100;
            
            ss << "    volatile int " << var << " = " << val1;
            if (op == 0) ss << " + " << val2 << ";\n";
            else if (op == 1) ss << " - " << val2 << ";\n";
            else if (op == 2) ss << " * " << val2 << ";\n";
            else ss << " ^ " << val2 << ";\n";
            
            if (rand() % 3 == 0) {
                 ss << "    if (" << var << " > " << (val1+val2) << ") { " << var << " = 0; }\n";
            }
        }
        ss << "}\n";
        ss << "// JUNK CODE END\n";
        return ss.str();
    }

    void Render() {
        ImGui::Text("StealSense C++ Code Protector");
        ImGui::Separator();
        
        ImGui::Text("Input String to Protect:");
        ImGui::InputTextMultiline("##source", inputBuffer, IM_ARRAYSIZE(inputBuffer), ImVec2(-1.0f, 60.0f));
        
        ImGui::Spacing();
        
        ImGui::Checkbox("Enable XOR String Encryption", &enableXor);
        ImGui::SliderInt("Generate Junk Lines", &junkLines, 0, 50);

        if (ImGui::Button("OBFUSCATE & GENERATE C++", ImVec2(-1.0f, 40.0f))) {
            std::stringstream result;
            
            result << "// Generated by StealSense Protector\n";
            result << "#include <iostream>\n\n";
            
            if (junkLines > 0)
                result << GenerateJunkCode(junkLines) << "\n";
            
            if (enableXor) {
                std::string input(inputBuffer);
                result << ObfuscateString(input, "encrypted_secret");
                result << "std::cout << \"Decrypted: \" << encrypted_secret << std::endl;\n";
            } else {
                result << "// String encryption disabled.\n";
            }
            
            if (junkLines > 0)
                result << "\n" << GenerateJunkCode(junkLines / 2);

            std::string resStr = result.str();
            if (resStr.length() < sizeof(outputBuffer))
                strcpy_s(outputBuffer, resStr.c_str());
            else
                strcpy_s(outputBuffer, "Error: Output buffer verify overflow.");
        }

        ImGui::Spacing();
        ImGui::Separator();
        ImGui::Text("Obfuscated Output (Copy this to your project):");
        ImGui::InputTextMultiline("##output", outputBuffer, IM_ARRAYSIZE(outputBuffer), ImVec2(-1.0f, -1.0f));
    }
}
